Add effects to RGB LED
Schluggi/AIOsense pull request #102
Opened 2023-08-02 19:03 UTC by btli

Home Alarm system is integrated with HA. This is a small addition to give AIOsense the ability to use a few LED effects and provide a visual indicator as these are placed in every room of the house. Also, made the strobing configurable since the default timings are a bit too calm for my preferences.

2023-08-02 19:46 UTC, Schluggi commented
Looks nice. I'll check this soon :)

2023-08-03 07:43 UTC, Schluggi requested changes

2023-08-03 07:43 UTC, Schluggi commented on esphome/packages/sensors/rgb_led.yaml
> +  strobe_on: 50ms
Please prefix your substitutions with `rgb_led_effects_` and add them also as a comment to the `esphome.yaml`.

2023-08-03 19:49 UTC, Schluggi approved these changes

2023-08-03 19:50 UTC, Schluggi commented
Please fix the ynal linting. You can ignore all "line too long" errors.

2023-08-03 22:31 UTC, btli commented
Don't have a D1 to test, but tried compiling. LED doesn't support pulse effect, so removed that. Should be passing tests now.

2023-08-03 22:34 UTC, merged